name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - protobuf<4
  - ipykernel
  - jupyterlab=3.0.12
  - seaborn=0.11.1
  - jinja2<3.1.0
  - pandas=1.2.3
  - pandas-profiling=2.11.0
  - pyarrow=2.0
  - wandb